[mypy]
python_version = 3.12
strict = True
warn_unused_ignores = True
plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin
exclude = backend/alembic

[mypy-celery.*]
ignore_missing_imports = True

[mypy-aiogram.*]
ignore_missing_imports = True

[mypy-asyncmy.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-croniter.*]
ignore_missing_imports = True

[mypy-nectarine_worker.tasks]
disallow_untyped_decorators = False
