"""add operational entities."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a28c3404f79'
down_revision: Union[str, None] = 'f5b6f44750b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_table('cron_jobs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('expression', sa.String(length=120), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cron_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cron_jobs'))
    )
    op.create_index(op.f('ix_cron_jobs_project_id'), 'cron_jobs', ['project_id'], unique=False)
    op.create_table('file_operations',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_file_operations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_operations'))
    )
    op.create_index(op.f('ix_file_operations_project_id'), 'file_operations', ['project_id'], unique=False)
    op.create_table('project_runtimes',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('runtime_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_runtimes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_runtimes')),
    sa.UniqueConstraint('project_id', name=op.f('uq_project_runtimes_project_id'))
    )
    op.create_table('project_sources',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('repository_url', sa.String(length=2048), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('encrypted_credential', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_sources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_sources')),
    sa.UniqueConstraint('project_id', name=op.f('uq_project_sources_project_id'))
    )
    op.create_table('backup_items',
    sa.Column('backup_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], name=op.f('fk_backup_items_backup_id_backups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_items'))
    )
    op.create_index(op.f('ix_backup_items_backup_id'), 'backup_items', ['backup_id'], unique=False)
    op.create_table('database_users',
    sa.Column('database_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=63), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('privileges', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['database_instances.id'], name=op.f('fk_database_users_database_id_database_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database_users'))
    )
    op.create_index(op.f('ix_database_users_database_id'), 'database_users', ['database_id'], unique=False)
    op.create_table('deployment_logs',
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stream', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_deployment_logs_deployment_id_deployments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_logs'))
    )
    op.create_index('ix_deployment_logs_order', 'deployment_logs', ['deployment_id', 'sequence'], unique=False)
    op.create_table('ssl_certificates',
    sa.Column('domain_id', sa.String(length=36), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_ssl_certificates_domain_id_domains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ssl_certificates')),
    sa.UniqueConstraint('domain_id', name=op.f('uq_ssl_certificates_domain_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ssl_certificates')
    op.drop_index('ix_deployment_logs_order', table_name='deployment_logs')
    op.drop_table('deployment_logs')
    op.drop_index(op.f('ix_database_users_database_id'), table_name='database_users')
    op.drop_table('database_users')
    op.drop_index(op.f('ix_backup_items_backup_id'), table_name='backup_items')
    op.drop_table('backup_items')
    op.drop_table('project_sources')
    op.drop_table('project_runtimes')
    op.drop_index(op.f('ix_file_operations_project_id'), table_name='file_operations')
    op.drop_table('file_operations')
    op.drop_index(op.f('ix_cron_jobs_project_id'), table_name='cron_jobs')
    op.drop_table('cron_jobs')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

