"""add backup policies."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92f7abe8d970'
down_revision: Union[str, None] = 'c6255be9d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_policies',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=False),
    sa.Column('retention_count', sa.Integer(), nullable=False),
    sa.Column('include_items', sa.JSON(), nullable=False),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_backup_policies_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_policies')),
    sa.UniqueConstraint('project_id', name=op.f('uq_backup_policies_project_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_policies')
    # ### end Alembic commands ###

