"""add sftp accounts."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c6255be9d3e4'
down_revision: Union[str, None] = '0a28c3404f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sftp_accounts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('public_key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sftp_accounts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sftp_accounts')),
    sa.UniqueConstraint('project_id', name=op.f('uq_sftp_accounts_project_id')),
    sa.UniqueConstraint('username', name=op.f('uq_sftp_accounts_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sftp_accounts')
    # ### end Alembic commands ###

